apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: codeflare-operator-bundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codeflare-operator-bundle
    app.kubernetes.io/part-of: codeflare-operator
  name: codeflare-operator-bundle
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: codeflare-operator-bundle
status:
  loadBalancer: {}
